import argparse
import base64
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
import csv
import datetime as dt
import hashlib
import json
import logging
import mimetypes
import random
import time
import urllib.error
import urllib.request
from collections import defaultdict
from pathlib import Path

from PIL import Image
from pymongo import MongoClient
from tqdm import tqdm


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

DEFAULT_MONGO_URI = "mongodb://localhost:27017/"
DEFAULT_DB_NAME = "sina_news_dataset_test"


def parse_args():
    parser = argparse.ArgumentParser(
        description="API-only image quality annotation from script-7 usable image pool"
    )

    parser.add_argument("--mongo-uri", default=DEFAULT_MONGO_URI, help="MongoDB URI")
    parser.add_argument("--db-name", default=DEFAULT_DB_NAME, help="MongoDB database name")
    parser.add_argument("--start-year", type=int, default=2014)
    parser.add_argument("--end-year", type=int, default=2026)
    parser.add_argument("--years", type=str, default="", help="Comma-separated years, overrides start/end")

    parser.add_argument(
        "--source-image-field",
        choices=["high_quality_images", "processed_images", "all_images"],
        default="high_quality_images",
        help="Image list field from year_2 docs generated by script 7",
    )
    parser.add_argument(
        "--require-high-quality-doc",
        action="store_true",
        default=True,
        help="Only read docs where has_high_quality_images=True",
    )
    parser.add_argument("--no-require-high-quality-doc", dest="require_high_quality_doc", action="store_false")

    parser.add_argument("--max-items", type=int, default=0, help="0 means all")
    parser.add_argument(
        "--max-items-per-year",
        type=int,
        default=0,
        help="Limit items per year before applying global --max-items. 0 means no per-year limit.",
    )
    parser.add_argument(
        "--balance-years-for-max-items",
        action="store_true",
        help="When --max-items is set, allocate quota evenly across years.",
    )
    parser.add_argument(
        "--shuffle-candidates",
        action="store_true",
        help="Shuffle candidates before global truncation to reduce chronological bias.",
    )
    parser.add_argument("--sample-size", type=int, default=0, help="0 means no sampling")
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument(
        "--artifacts-dir",
        default="ai_image_annotation/run_artifacts",
        help="Directory for outputs: status/checkpoint/summary/csv",
    )
    parser.add_argument("--output-csv", default="ai_image_annotations.csv")
    parser.add_argument("--output-jsonl", default="ai_image_annotations.jsonl")

    parser.add_argument("--checkpoint-every", type=int, default=200)
    parser.add_argument("--resume", action="store_true", help="Resume from output CSV")
    parser.add_argument("--reprocess", action="store_true", help="Ignore existing output and rebuild")

    parser.add_argument("--accept-threshold", type=float, default=0.75)
    parser.add_argument("--review-threshold", type=float, default=0.55)

    parser.add_argument(
        "--auth-file",
        default="ai_image_annotation/local_auth.json",
        help="Local auth JSON file (ignored by git)",
    )
    parser.add_argument(
        "--api-models",
        default="",
        help="Comma-separated models. Overrides models in auth-file when provided.",
    )
    parser.add_argument("--api-timeout", type=int, default=60)
    parser.add_argument("--api-max-retries", type=int, default=2)
    parser.add_argument("--workers", type=int, default=6, help="Concurrent workers for annotation")
    parser.add_argument(
        "--primary-model",
        type=str,
        default="",
        help="Primary model used first. Defaults to first model in auth config.",
    )
    parser.add_argument(
        "--escalate-band",
        type=float,
        default=0.08,
        help="If primary score falls in [review-threshold-band, accept-threshold+band], run secondary models.",
    )
    parser.add_argument(
        "--no-escalation",
        dest="enable_escalation",
        action="store_false",
        help="Disable secondary-model escalation and use only primary model.",
    )
    parser.set_defaults(enable_escalation=True)
    parser.add_argument(
        "--force-full-ensemble",
        action="store_true",
        help="Always run all configured models for every image (original multi-model behavior).",
    )

    args = parser.parse_args()

    if args.checkpoint_every < 1:
        raise ValueError("--checkpoint-every must be >= 1")
    if args.max_items < 0:
        raise ValueError("--max-items must be >= 0")
    if args.max_items_per_year < 0:
        raise ValueError("--max-items-per-year must be >= 0")
    if args.sample_size < 0:
        raise ValueError("--sample-size must be >= 0")
    if not (0 <= args.review_threshold <= 1 and 0 <= args.accept_threshold <= 1):
        raise ValueError("thresholds must be in [0,1]")
    if args.review_threshold > args.accept_threshold:
        raise ValueError("--review-threshold must be <= --accept-threshold")
    if args.workers < 1:
        raise ValueError("--workers must be >= 1")
    if not (0 <= args.escalate_band <= 0.5):
        raise ValueError("--escalate-band must be in [0,0.5]")

    return args


def build_years(args):
    if args.years.strip():
        return sorted({int(x.strip()) for x in args.years.split(",") if x.strip()})
    return list(range(args.start_year, args.end_year + 1))


def atomic_write_json(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    tmp.replace(path)


def image_id_from_path(path: str):
    return hashlib.md5(path.encode("utf-8")).hexdigest()


def load_auth_config(auth_file: Path):
    if not auth_file.exists():
        raise FileNotFoundError(
            f"auth file not found: {auth_file}. Create it from local_auth.example.json"
        )

    with auth_file.open("r", encoding="utf-8") as f:
        cfg = json.load(f)

    api_key = cfg.get("api_key") or cfg.get("login_code")
    api_base_url = cfg.get("api_base_url", "").rstrip("/")
    models = cfg.get("models", [])

    if not api_key:
        raise ValueError("auth file missing api_key/login_code")
    if not api_base_url:
        raise ValueError("auth file missing api_base_url")
    if not models:
        raise ValueError("auth file missing models list")

    return {
        "api_key": api_key,
        "api_base_url": api_base_url,
        "models": models,
    }


def image_to_data_uri(image_path: Path):
    mime, _ = mimetypes.guess_type(str(image_path))
    if not mime:
        mime = "image/jpeg"
    with image_path.open("rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return f"data:{mime};base64,{b64}"


def extract_json_object(text):
    if not text:
        return None
    text = text.strip()
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    try:
        return json.loads(text[start : end + 1])
    except json.JSONDecodeError:
        return None


def call_vision_api(api_base_url, api_key, model, image_path, timeout=60, max_retries=2):
    data_uri = image_to_data_uri(Path(image_path))
    prompt = (
        "You are labeling financial-news image quality for model training selection. "
        "Return only JSON with keys: quality_score (0-1), "
        "label (quality_pass_auto_accept|quality_review_needed|quality_fail_candidate), "
        "reason (short), text_heavy (0-1), blur_level (0-1)."
    )

    payload = {
        "model": model,
        "temperature": 0,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": data_uri}},
                ],
            }
        ],
    }

    url = f"{api_base_url}/chat/completions"
    body = json.dumps(payload).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }

    last_err = ""
    for attempt in range(max_retries + 1):
        try:
            req = urllib.request.Request(url, data=body, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                response_data = json.loads(resp.read().decode("utf-8"))

            choices = response_data.get("choices", [])
            if not choices:
                raise ValueError("API response missing choices")

            content = choices[0].get("message", {}).get("content", "")
            parsed = extract_json_object(content)
            if not parsed:
                raise ValueError(f"model response is not valid JSON: {content[:200]}")

            score = float(parsed.get("quality_score", 0.0))
            score = max(0.0, min(1.0, score))

            return {
                "quality_score": round(score, 6),
                "label": parsed.get("label", "quality_review_needed"),
                "reason": str(parsed.get("reason", ""))[:300],
                "text_heavy": float(parsed.get("text_heavy", 0.0)),
                "blur_level": float(parsed.get("blur_level", 0.0)),
                "raw": parsed,
            }
        except (urllib.error.URLError, urllib.error.HTTPError, ValueError, json.JSONDecodeError) as exc:
            last_err = str(exc)
            if attempt < max_retries:
                time.sleep(1.2 * (attempt + 1))
                continue
            break

    raise RuntimeError(f"API call failed for model={model}: {last_err}")


def aggregate_api_results(model_results, errors):
    if not model_results:
        raise RuntimeError("all API models failed: " + " | ".join(errors[:3]))

    avg_score = sum([x["quality_score"] for x in model_results]) / len(model_results)
    label_counts = {}
    for x in model_results:
        label_counts[x["label"]] = label_counts.get(x["label"], 0) + 1
    majority_label = sorted(label_counts.items(), key=lambda x: (-x[1], x[0]))[0][0]
    agreement = max(label_counts.values()) / len(model_results)

    return {
        "quality_score": round(float(avg_score), 6),
        "predicted_quality_label": majority_label,
        "api_agreement": round(float(agreement), 6),
        "api_votes": json.dumps(label_counts, ensure_ascii=False),
        "api_models_used": ",".join([x["model"] for x in model_results]),
        "api_error": " | ".join(errors[:3]),
    }


def run_api_models(image_path: str, api_conf, models, timeout, max_retries):
    model_results = []
    errors = []

    for model in models:
        try:
            result = call_vision_api(
                api_base_url=api_conf["api_base_url"],
                api_key=api_conf["api_key"],
                model=model,
                image_path=image_path,
                timeout=timeout,
                max_retries=max_retries,
            )
            model_results.append({"model": model, **result})
        except Exception as exc:
            errors.append(f"{model}:{exc}")

    return model_results, errors


def run_api_ensemble(image_path: str, api_conf, timeout, max_retries):
    model_results, errors = run_api_models(
        image_path=image_path,
        api_conf=api_conf,
        models=api_conf["models"],
        timeout=timeout,
        max_retries=max_retries,
    )
    return aggregate_api_results(model_results, errors)


def run_primary_with_optional_escalation(
    image_path: str,
    api_conf,
    primary_model: str,
    secondary_models,
    timeout,
    max_retries,
    args_force_full_ensemble: bool,
    enable_escalation: bool,
    review_threshold: float,
    accept_threshold: float,
    escalate_band: float,
):
    primary_results, primary_errors = run_api_models(
        image_path=image_path,
        api_conf=api_conf,
        models=[primary_model],
        timeout=timeout,
        max_retries=max_retries,
    )
    if not primary_results:
        raise RuntimeError("primary model failed: " + " | ".join(primary_errors[:3]))

    primary_score = float(primary_results[0]["quality_score"])
    if args_force_full_ensemble:
        secondary_results, secondary_errors = run_api_models(
            image_path=image_path,
            api_conf=api_conf,
            models=secondary_models,
            timeout=timeout,
            max_retries=max_retries,
        )
        return aggregate_api_results(primary_results + secondary_results, primary_errors + secondary_errors)

    low = max(0.0, review_threshold - escalate_band)
    high = min(1.0, accept_threshold + escalate_band)
    need_escalation = enable_escalation and len(secondary_models) > 0 and (low <= primary_score <= high)

    if not need_escalation:
        return aggregate_api_results(primary_results, primary_errors)

    secondary_results, secondary_errors = run_api_models(
        image_path=image_path,
        api_conf=api_conf,
        models=secondary_models,
        timeout=timeout,
        max_retries=max_retries,
    )
    return aggregate_api_results(primary_results + secondary_results, primary_errors + secondary_errors)


def review_priority(score: float, agreement: float):
    if agreement < 0.67:
        return "high"
    if score < 0.55:
        return "high"
    if score < 0.75:
        return "medium"
    return "low"


def normalize_label(score: float, label: str, accept_threshold: float, review_threshold: float):
    if label in {"quality_pass_auto_accept", "quality_review_needed", "quality_fail_candidate"}:
        return label
    if score >= accept_threshold:
        return "quality_pass_auto_accept"
    if score >= review_threshold:
        return "quality_review_needed"
    return "quality_fail_candidate"


def load_processed_paths(csv_path: Path):
    processed = set()
    if not csv_path.exists():
        return processed
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            img_path = row.get("image_path")
            if img_path:
                processed.add(img_path)
    return processed


def safe_image_meta(image_path: str):
    try:
        with Image.open(image_path) as img:
            w, h = img.size
            return int(w), int(h)
    except Exception:
        return 0, 0


def collect_candidates_from_script7(args, years):
    client = MongoClient(args.mongo_uri)
    db = client[args.db_name]

    candidates = []
    seen_paths = set()

    try:
        for year in years:
            collection_name = f"{year}_2"
            if collection_name not in db.list_collection_names():
                logging.warning("collection missing, skip: %s", collection_name)
                continue

            col = db[collection_name]
            query = {}
            if args.require_high_quality_doc:
                query["has_high_quality_images"] = True

            projection = {
                "news_date": 1,
                "link": 1,
                "title": 1,
                "has_high_quality_images": 1,
                args.source_image_field: 1,
            }

            cursor = col.find(query, projection)
            for doc in cursor:
                images = doc.get(args.source_image_field, []) or []
                for img in images:
                    abs_path = str(img.get("abs_path") or "").strip()
                    rel_path = str(img.get("path") or "").strip()
                    if not abs_path:
                        continue
                    if abs_path in seen_paths:
                        continue
                    if not Path(abs_path).exists():
                        continue
                    seen_paths.add(abs_path)
                    candidates.append(
                        {
                            "year": year,
                            "news_date": str(doc.get("news_date") or ""),
                            "link": str(doc.get("link") or ""),
                            "title": str(doc.get("title") or ""),
                            "image_path": abs_path,
                            "image_rel_path": rel_path,
                            "source_collection": collection_name,
                            "source_field": args.source_image_field,
                        }
                    )
    finally:
        client.close()

    return candidates


def apply_year_limit(candidates, max_items_per_year, seed):
    if max_items_per_year <= 0:
        return candidates

    by_year = defaultdict(list)
    for item in candidates:
        by_year[item["year"]].append(item)

    rng = random.Random(seed)
    limited = []
    for year in sorted(by_year.keys()):
        items = by_year[year]
        if len(items) > max_items_per_year:
            rng.shuffle(items)
            items = items[:max_items_per_year]
        limited.extend(items)
    return limited


def apply_balanced_global_limit(candidates, max_items, seed):
    if max_items <= 0 or not candidates:
        return candidates

    by_year = defaultdict(list)
    for item in candidates:
        by_year[item["year"]].append(item)

    years = sorted(by_year.keys())
    n_years = len(years)
    if n_years == 0:
        return candidates

    rng = random.Random(seed)
    for year in years:
        rng.shuffle(by_year[year])

    base = max_items // n_years
    extra = max_items % n_years
    selected = []
    remainder = []

    for idx, year in enumerate(years):
        quota = base + (1 if idx < extra else 0)
        picked = by_year[year][:quota]
        selected.extend(picked)
        remainder.extend(by_year[year][quota:])

    if len(selected) < max_items and remainder:
        rng.shuffle(remainder)
        selected.extend(remainder[: max_items - len(selected)])

    return selected[:max_items]


def append_rows(csv_path: Path, jsonl_path: Path, rows, write_header=False):
    fieldnames = [
        "image_id",
        "year",
        "news_date",
        "link",
        "title",
        "source_collection",
        "source_field",
        "image_path",
        "image_rel_path",
        "width",
        "height",
        "quality_score",
        "predicted_quality_label",
        "review_priority",
        "api_agreement",
        "api_votes",
        "api_models_used",
        "api_error",
        "human_decision",
        "human_label",
        "human_notes",
        "created_at",
    ]

    with csv_path.open("a", encoding="utf-8", newline="") as cf, jsonl_path.open("a", encoding="utf-8") as jf:
        writer = csv.DictWriter(cf, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()

        for row in rows:
            writer.writerow(row)
            jf.write(json.dumps(row, ensure_ascii=False) + "\n")


def annotate_one_item(item, args, api_conf, primary_model, secondary_models):
    image_path = item["image_path"]
    row = {
        "image_id": image_id_from_path(image_path),
        "year": item["year"],
        "news_date": item["news_date"],
        "link": item["link"],
        "title": item["title"],
        "source_collection": item["source_collection"],
        "source_field": item["source_field"],
        "image_path": image_path,
        "image_rel_path": item["image_rel_path"],
        "human_decision": "",
        "human_label": "",
        "human_notes": "",
        "created_at": dt.datetime.now().isoformat(),
    }

    try:
        width, height = safe_image_meta(image_path)
        api_result = run_primary_with_optional_escalation(
            image_path=image_path,
            api_conf=api_conf,
            primary_model=primary_model,
            secondary_models=secondary_models,
            timeout=args.api_timeout,
            max_retries=args.api_max_retries,
            args_force_full_ensemble=args.force_full_ensemble,
            enable_escalation=args.enable_escalation,
            review_threshold=args.review_threshold,
            accept_threshold=args.accept_threshold,
            escalate_band=args.escalate_band,
        )

        score = float(api_result["quality_score"])
        label = normalize_label(
            score=score,
            label=api_result["predicted_quality_label"],
            accept_threshold=args.accept_threshold,
            review_threshold=args.review_threshold,
        )
        agreement = float(api_result["api_agreement"])

        row.update(
            {
                "width": width,
                "height": height,
                "quality_score": round(score, 6),
                "predicted_quality_label": label,
                "review_priority": review_priority(score, agreement),
                "api_agreement": round(agreement, 6),
                "api_votes": api_result["api_votes"],
                "api_models_used": api_result["api_models_used"],
                "api_error": api_result["api_error"],
            }
        )
        return row, label, False
    except Exception as exc:
        width, height = safe_image_meta(image_path)
        row.update(
            {
                "width": width,
                "height": height,
                "quality_score": 0,
                "predicted_quality_label": "error",
                "review_priority": "high",
                "api_agreement": 0,
                "api_votes": "",
                "api_models_used": ",".join(api_conf["models"]),
                "api_error": str(exc)[:600],
                "human_notes": f"auto_error:{exc}",
            }
        )
        return row, "error", True


def main():
    args = parse_args()
    random.seed(args.seed)

    years = build_years(args)
    artifacts_dir = Path(args.artifacts_dir)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    status_path = artifacts_dir / "ai_image_quality_annotator_status.json"
    checkpoint_path = artifacts_dir / "ai_image_quality_annotator_checkpoint.json"
    summary_path = artifacts_dir / "ai_image_quality_annotator_summary.json"
    csv_path = artifacts_dir / args.output_csv
    jsonl_path = artifacts_dir / args.output_jsonl

    if args.reprocess:
        for p in [csv_path, jsonl_path, checkpoint_path]:
            if p.exists():
                p.unlink()

    api_conf = load_auth_config(Path(args.auth_file))
    if args.api_models.strip():
        api_conf["models"] = [m.strip() for m in args.api_models.split(",") if m.strip()]

    primary_model = args.primary_model.strip() if args.primary_model else api_conf["models"][0]
    if primary_model not in api_conf["models"]:
        api_conf["models"] = [primary_model] + [m for m in api_conf["models"] if m != primary_model]
    secondary_models = [m for m in api_conf["models"] if m != primary_model]

    masked = api_conf["api_key"][:3] + "***" + api_conf["api_key"][-3:]
    logging.info("API enabled. base_url=%s, models=%s, key=%s", api_conf["api_base_url"], api_conf["models"], masked)
    logging.info(
        "Run strategy: workers=%d, primary_model=%s, escalation=%s, escalate_band=%.3f",
        args.workers,
        primary_model,
        args.enable_escalation,
        args.escalate_band,
    )

    run_id = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    status = {
        "script": "ai_image_quality_annotator.py",
        "run_id": run_id,
        "started_at": dt.datetime.now().isoformat(),
        "last_updated": dt.datetime.now().isoformat(),
        "phase": "collecting_candidates",
        "completed": False,
        "config": vars(args),
        "years": years,
    }
    atomic_write_json(status_path, status)

    candidates = collect_candidates_from_script7(args, years)

    candidates = apply_year_limit(candidates, args.max_items_per_year, args.seed)

    if args.sample_size and 0 < args.sample_size < len(candidates):
        candidates = random.sample(candidates, args.sample_size)

    if args.shuffle_candidates:
        random.shuffle(candidates)

    if args.max_items and args.max_items > 0 and args.balance_years_for_max_items:
        candidates = apply_balanced_global_limit(candidates, args.max_items, args.seed)

    if args.max_items and args.max_items > 0:
        candidates = candidates[: args.max_items]

    processed_paths = set()
    if args.resume and not args.reprocess:
        processed_paths = load_processed_paths(csv_path)

    todo = [x for x in candidates if x["image_path"] not in processed_paths]

    status.update(
        {
            "phase": "annotating",
            "last_updated": dt.datetime.now().isoformat(),
            "total_candidates": len(candidates),
            "already_processed": len(processed_paths),
            "to_process": len(todo),
        }
    )
    atomic_write_json(status_path, status)

    if not todo:
        status.update(
            {
                "phase": "completed",
                "completed": True,
                "last_updated": dt.datetime.now().isoformat(),
                "message": "No new images to process",
            }
        )
        atomic_write_json(status_path, status)
        summary = {
            "script": "ai_image_quality_annotator.py",
            "run_id": run_id,
            "status": "completed",
            "reason": "no_new_images",
            "total_candidates": len(candidates),
            "processed": 0,
            "artifacts_dir": str(artifacts_dir),
            "finished_at": dt.datetime.now().isoformat(),
        }
        atomic_write_json(summary_path, summary)
        logging.info("No new images to process.")
        return

    label_counter = {
        "quality_pass_auto_accept": 0,
        "quality_review_needed": 0,
        "quality_fail_candidate": 0,
        "error": 0,
    }

    write_header = not csv_path.exists()
    buffer_rows = []
    processed = 0
    failed = 0
    start_ts = dt.datetime.now()
    finished_count = 0
    inflight_limit = max(args.workers * 2, args.workers)
    todo_iter = iter(todo)
    futures = {}
    last_image_path = ""

    def submit_next(executor):
        try:
            next_item = next(todo_iter)
        except StopIteration:
            return False
        fut = executor.submit(annotate_one_item, next_item, args, api_conf, primary_model, secondary_models)
        futures[fut] = next_item
        return True

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        for _ in range(inflight_limit):
            if not submit_next(executor):
                break

        with tqdm(total=len(todo), desc="Annotating images") as pbar:
            while futures:
                done, _ = wait(futures.keys(), return_when=FIRST_COMPLETED)
                for fut in done:
                    item = futures.pop(fut)
                    image_path = item["image_path"]
                    last_image_path = image_path
                    row, label, is_failed = fut.result()

                    if is_failed:
                        failed += 1
                        label_counter["error"] += 1
                    else:
                        processed += 1
                        label_counter[label] += 1

                    buffer_rows.append(row)
                    finished_count += 1
                    pbar.update(1)

                    if len(buffer_rows) >= 100:
                        append_rows(csv_path, jsonl_path, buffer_rows, write_header=write_header)
                        write_header = False
                        buffer_rows = []

                    if finished_count % args.checkpoint_every == 0:
                        checkpoint_payload = {
                            "run_id": run_id,
                            "last_updated": dt.datetime.now().isoformat(),
                            "processed_in_this_run": processed,
                            "failed_in_this_run": failed,
                            "last_image_path": image_path,
                            "label_counter": label_counter,
                        }
                        atomic_write_json(checkpoint_path, checkpoint_payload)

                        status.update(
                            {
                                "last_updated": dt.datetime.now().isoformat(),
                                "processed_in_this_run": processed,
                                "failed_in_this_run": failed,
                                "progress": f"{finished_count}/{len(todo)}",
                            }
                        )
                        atomic_write_json(status_path, status)

                    submit_next(executor)

    if buffer_rows:
        append_rows(csv_path, jsonl_path, buffer_rows, write_header=write_header)

    checkpoint_payload = {
        "run_id": run_id,
        "last_updated": dt.datetime.now().isoformat(),
        "processed_in_this_run": processed,
        "failed_in_this_run": failed,
        "last_image_path": last_image_path,
        "label_counter": label_counter,
    }
    atomic_write_json(checkpoint_path, checkpoint_payload)

    duration_seconds = int((dt.datetime.now() - start_ts).total_seconds())

    summary = {
        "script": "ai_image_quality_annotator.py",
        "run_id": run_id,
        "status": "completed",
        "started_at": start_ts.isoformat(),
        "finished_at": dt.datetime.now().isoformat(),
        "duration_seconds": duration_seconds,
        "years": years,
        "source": {
            "mongo_uri": args.mongo_uri,
            "db_name": args.db_name,
            "source_image_field": args.source_image_field,
            "require_high_quality_doc": args.require_high_quality_doc,
        },
        "total_candidates": len(candidates),
        "processed_in_this_run": processed,
        "failed_in_this_run": failed,
        "label_counter": label_counter,
        "artifacts": {
            "status": str(status_path),
            "checkpoint": str(checkpoint_path),
            "summary": str(summary_path),
            "output_csv": str(csv_path),
            "output_jsonl": str(jsonl_path),
        },
        "config": vars(args),
    }
    atomic_write_json(summary_path, summary)

    status.update(
        {
            "phase": "completed",
            "completed": True,
            "last_updated": dt.datetime.now().isoformat(),
            "processed_in_this_run": processed,
            "failed_in_this_run": failed,
        }
    )
    atomic_write_json(status_path, status)

    logging.info("Done. Processed=%d Failed=%d", processed, failed)
    logging.info("Summary file: %s", summary_path)


if __name__ == "__main__":
    main()
